### ISSUE TITLE
Including URL in .env creates security issues with Netlify and other hosters....

### ISSUE THREAD

**Issue by PaulHaze** [nurullah/react-default#1]
HI,

So I am REALLY trying to get your plugin working as it is _exactly_ what I am needing for a project I am working on. Problem I have is, every time I try and upload it to Netlify or my own web hosting, the presence of the PUBLIC_URL seems to cause issues. It works fine with yours - and I have even cloned your repo and changed only the URL to see if I could get it working but to no avail.

![Screen Shot 2021-07-21 at 8 45 58 am](https://user-images.githubusercontent.com/20569604/126405233-f6e972c7-1f6a-415a-bd5f-4c9466117141.png)

Without adding the right URL into the .env I get an 'The Build URL is not validated.' when entering the short code. However I even tried it with your default page and I get the same error, so maybe it is not totally related to the .env file

![Screen Shot 2021-07-21 at 8 51 47 am](https://user-images.githubusercontent.com/20569604/126405275-3a6bb61a-2bf6-4d55-9955-0cf84dcf2ab5.png)

Is this plug in still working? I would love to know where I am going wrong thanks.

**Comment by nurullah** [comment]
Hi Paul.

Sorry for seeing your message late. The error you got because that the site defined at PUBLIC_URL did not found. The Embed React Build plugin reads the "https://embedtesting.netlify.app/asset-manifest.json" file and loads the required dependencies from it. You got that error because the URL you defined could not be found. It will work after deploying on Netlify.

By the way, you don't have to work with netlify. After you decide to place your build files under any domain (e.g: https://example.com/embedtesting), update the PUBLIC_URL information (PUBLIC_URL=https://example.com/embedtesting) and deploy. It will work after that.
